# Generated by Django 4.2.5 on 2023-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_user_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
    ]
